//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaripovMozaika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GaripovMozaikaEntities : DbContext
    {
        public GaripovMozaikaEntities()
            : base("name=GaripovMozaikaEntities")
        {
        }

        public static GaripovMozaikaEntities _context;
        public static GaripovMozaikaEntities GetContext()
        {
            if (_context == null)
                _context = new GaripovMozaikaEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material> Material { get; set; }
        public DbSet<Material_Type> Material_Type { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Product_Material> Product_Material { get; set; }
        public DbSet<Product_Type> Product_Type { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<Supplier_Type> Supplier_Type { get; set; }
    }
}
