//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaripovMozaika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Type
    {
        public Material_Type()
        {
            this.Material = new HashSet<Material>();
        }
    
        public int Material_Type_ID { get; set; }
        public string Material_Type_Name { get; set; }
        public decimal Material_Type_Proccent { get; set; }
    
        public virtual ICollection<Material> Material { get; set; }
    }
}
