//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaripovMozaika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Product_Material = new HashSet<Product_Material>();
        }
    
        public int Product_ID { get; set; }
        public long Product_Article { get; set; }
        public int Product_Type { get; set; }
    
        public virtual ICollection<Product_Material> Product_Material { get; set; }
        public virtual Product_Type Product_Type1 { get; set; }
    }
}
