//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaripovMozaika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Type
    {
        public Supplier_Type()
        {
            this.Supplier = new HashSet<Supplier>();
        }
    
        public int Supplier_Type1 { get; set; }
        public string Supplier_Type_Name { get; set; }
    
        public virtual ICollection<Supplier> Supplier { get; set; }
    }
}
