//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaripovMozaika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Material = new HashSet<Material>();
        }
    
        public int Supplier_ID { get; set; }
        public string Supplier_Name { get; set; }
        public int Supplier_Type { get; set; }
        public long Supplier_INN { get; set; }
        public int Supplier_Rating { get; set; }
        public System.DateTime Supplier_Date_Of_Start { get; set; }
    
        public virtual Supplier_Type Supplier_Type1 { get; set; }
        public virtual ICollection<Material> Material { get; set; }
    }
}
